credentials:
  usernames:
    emmanuel:
      email: morteyandrews@gmail.com
      #failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Andy Mortey
      password: "33333" # Will be hashed automatically
    
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - andy.mortey@azubiafrica.org